### ISSUE TITLE
macOS Sequoia is working

### ISSUE THREAD

**Issue by journey-ad** [ZeMooX/remove-finder-from-dock#1]
My device is MacBook Pro 14-inch, M4 Pro, macOS Sequoia 15.1.1 (24B2091).

The repo method works with slight adjustments:
- The plist file is located at `/System/Library/CoreServices/Dock.app/Contents/Resources/DockMenus.plist`
- The `bless` command requires the absolute path to CoreServices:
  `sudo bless --mount /Users/<your_username>/systemmount/System/Library/CoreServices --setBoot --create-snapshot`
- Other steps are consistent with the repo.

**Comment by ZeMooX** [comment]
Thank you for your feedback.

Sadly I can't validate newer OS versions at the moment, as I am reliant on the security features. Nevertheless I've worked in your suggestions in to the repository with attribution to you.

**Comment by Redwinam** [comment]
Thank you!!

**Comment by isqqcle** [comment]
Also working on Tahoe 26.5 (25F71). The plist file is also at `/System/Library/CoreServices/Dock.app/Contents/Resources/DockMenus.plist`.

Might be worth adding a note here, because this tripped me up:
https://github.com/ZeMooX/remove-finder-from-dock/blob/7147a6b8c361248be94bd83a1fc2d69bd23dff78/README.md#L120-L123

There is a lingering indicator where Finder was before removing it that doesn't disappear unless you disable 'Show indicators for open applications' (Desktop & Dock > Dock), then reenable after removing (mentioned [here](https://github.com/jesscxc/hide-finder-trash-dock-icons))

Additionally, I hid the Trash icon by adding the same entry to the `trash` array. This might be worth mentioning in the repo for anyone wondering.

Annoyingly, I haven't figured out how to hide the vertical separator, but honestly, it's useful enough to keep for resizing the Dock.
